### ISSUE TITLE
四国めたんを選択するとボット停止

### ISSUE THREAD

**Issue by mnsinri** [aria-music/zundacord#47]
`/voice`でボイスアクタとして四国めたんを選択すると、以下のエラーを吐いてボットが停止する

```
DiscordAPIError[50035]: Invalid Form Body
components[2].components[5][COMPONENT_LAYOUT_WIDTH_EXCEEDED]: The specified component exceeds the maximum width
    at handleErrors (/workspaces/zundacord/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/workspaces/zundacord/node_modules/@discordjs/rest/dist/index.js:736:23)
    at async REST.request (/workspaces/zundacord/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async StringSelectMenuInteraction.update (/workspaces/zundacord/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:233:5) {
  requestBody: {
    files: [],
    json: {
      type: 7,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,
        embeds: [
          {
            footer: [Object],
            color: 4568575,
            title: 'Select your voice!',
            fields: [Array]
          },
          {
            footer: [Object],
            color: 4568575,
            title: 'You need to agree to the terms of service',
            description: '四国めたんの音声ライブラリを用いて生成した音声は、\n' +
              '「VOICEVOX:四国めたん」とクレジットを記載すれば、商用・非商用で利用可能です。\n' +
              '\n' +
              '利用規約の詳細は以下をご確認ください。  \n' +
              'https://zunko.jp/con_ongen_kiyaku.html\n'
          }
        ],
        components: [
          { type: 1, components: [Array] },
          { type: 1, components: [Array] },
          { type: 1, components: [Array] }
        ],
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: {
    code: 50035,
    errors: {
      components: { '2': { components: { '5': [Object] } } }
    },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1104677528913846364/aW50ZXJhY3Rpb246MTEwNDY3NzUyODkxMzg0NjM2NDpHN25tRW1iMDluY21XWU1ESWRaNW9Td2pjV004dE1pVGhQWWhSYklZRm1HeWluVXA0UXg2UExZcHpzOVlHQUc1b21WbTVBQWcxVEVqMVFKSnllNng4ZUpWdVJXa1Bjc0dJR1ZJYktIczdSdHpxM3p6eVpUanVPcjRXYklmbHVDNg/callback'
}
```

**Comment by sarisia** [comment]
Discord の仕様でボタンは横に5つしか並べられないけど四国めたん, ずんだもんはスタイルが6個以上存在するのでその辺の処理をやってなくて壊れてる

#14 で修正予定
